export const tagReference={ 
    aceAttorney: "Ace Attorney",
    agneteKjolsrud: "Agnete Kjølsrud",
    aionOnline: "Aion Online",
    alderaminOnTheSky: "Alderamin on the Sky",
    amnesia: "Amnesia",
    angelBeats: "Angel Beats!",
    aquarianAge: "Aquarian Age",
    arNosurge: "Ar Nosurge",
    arTonelico: "Ar Tonelico",
    arcRiseFantasia: "Arc Rise Fantasia",
    artistsMangakas: "Artists & Mangakas",
    artworkByAkihikoYoshida: "Artwork by Akihiko Yoshida",
    artworkByAkioWatanabe: "Artwork by Akio Watanabe",
    artworkByCarnelian: "Artwork by Carnelian",
    artworkByChinatsuKurahana: "Artwork by Chinatsu Kurahana",
    artworkByCarol: "Artwork by Carol",
    artworkByClamp: "Artwork by CLAMP",
    artworkByFujiwara: "Artwork by Fujiwara",
    artworkByHigashiguchiChuuo: "Artwork by Higashiguchi Chuuo",
    artworkByHonyarara: "Artwork by Honyarara",
    artworkByHuke: "Artwork by Huke",
    artworkByHyunKyoungup: "Artwork by Hyun Kyoungup",
    artworkByHyungTaeKim: "Artwork by Hyung Tae Kim",
    artworkByInutarou: "Artwork by Inutarou",
    artworkByKantako: "Artwork by Kantako",
    artworkByKazumiIkeda: "Artwork by Kazumi Ikeda",
    artworkByLange: "Artwork by Lange",
    artworkByMisakuraNankotsu: "Artwork by Misakura Nankotsu",
    artworkByMitsuiMana: "Artwork by Mitsui Mana",
    artworkByMiwaShirow: "Artwork by Miwa Shirow",
    artworkByMiyamaZero: "Artwork by Miyama Zero",
    artworkByNardack: "Artwork by Nardack",
    artworkByNoiziIto: "Artwork by Noizi Ito",
    artworkByPako: "Artwork by Pako",
    artworkByPeachPit: "Artwork by Peach-Pit",
    artworkByPoco: "Artwork by Poco",
    artworkByQianYeQys3: "Artwork by Qian Ye QYS3",
    artworkByRangeMurata: "Artwork by Range Murata",
    artworkByRanou: "Artwork by Ran'ou",
    artworkByRedjuice: "Artwork by Redjuice",
    artworkByRiv: "Artwork by Riv",
    artworkByRyouNagi: "Artwork by Ryou Nagi",
    artworkBySakakiMaki: "Artwork by Sakaki Maki",
    artworkBySantaTsuji: "Artwork by Santa Tsuji",
    artworkBySayori: "Artwork by Sayori",
    artworkBySerenade: "Artwork by Serenade",
    artworkByShibamotoThores: "Artwork by Shibamoto Thores",
    artworkByShigenoriSoejima: "Artwork by Shigenori Soejima",
    artworkByShigetoKoyama: "Artwork by Shigeto Koyama",
    artworkByTetsuyaNomura: "Artwork by Tetsuya Nomura",
    artworkByTinkerbell: "Artwork by Tinkerbell",
    artworkByTohruKousaka: "Artwork by Tohru Kousaka",
    artworkByTonyTaka: "Artwork by Tony Taka",
    artworkByTooruMizutani: "Artwork by Tooru Mizutani",
    artworkByTsukioka: "Artwork by Tsukioka",
    artworkByTsunako: "Artwork by Tsunako",
    artworkByUgetsuHakua: "Artwork by Ugetsu Hakua",
    artworkByYujiShiozaki: "artwork by Yuji Shiozaki",
    artworkByYukiruSugisaki: "Artwork by Yukiru Sugisaki",
    artworkByYuuAmano: "Artwork by Yuu Amano",
    artworkByZihling: "Artwork by Zihling",
    asuraOnline: "Asura Online",
    atlanticaOnline: "Atlantica Online",
    bakemonogatari: "Bakemonogatari",
    bayonetta: "Bayonetta",
    beatless: "BEATLESS",
    bGataHKei: "B Gata H Kei",
    blackRockShooter: "Black Rock Shooter",
    bladeSoul: "Blade & Soul",
    blazblue: "Blazblue",
    bloodyRondo: "Bloody Rondo",
    bravelyDefault: "Bravely Default",
    bravelySecond: "Bravely Second",
    burstAngel: "Burst Angel",
    busGamer: "Bus Gamer",
    cardcaptorSakura: "Cardcaptor Sakura",
    cartagra: "Cartagra",
    catherine: "Catherine",
    chaikaTheCoffinPrincess: "Chaika: The Coffin Princess",
    chobits: "Chobits",
    chronoClock: "Chrono Clock",
    collarXMalice: "Collar x Malice",
    conceptionIi: "Conception II: Children of the Seven Stars",
    dateALive: "Date A Live",
    dearS: "DearS",
    deathNote: "Death Note",
    deepBlueSkyPureWhiteWings: "Deep Blue Sky & Pure White Wings",
    destinyChild: "Destiny Child",
    devilsDevelConcept: "Devils Devel Concept",
    dnAngel: "D.N.Angel",
    dogsBulletsCarnage: "Dogs: Bullets & Carnage",
    dota: "D.O.T.A",
    dramAticalMurder: "DRAMAtical Murder",
    dungeonFighterOnline: "Dungeon Fighter Online",
    dungeonOfRegalias: "Dungeon of Regalias",
    elsword: "Elsword",
    eulenSpiegel: "Eulenspiegel",
    fatestayNight: "Fate / Stay Night",
    fairyFencerF: "Fairy Fencer F",
    finalFantasyX: "Final Fantasy X",
    finalFantasyX2: "Final Fantasy X-2",
    finalFantasyXiii: "Final Fantasy XIII",
    finalFantasyXiv: "Final Fantasy XIV",
    finalFantasyXv: "Final Fantasy XV",
    fiveStarStories: "Five Star Stories",
    forsakenWorld: "Forsaken World",
    fullmetalAlchemist: "Fullmetal Alchemist",
    futureDiary: "Future Diary",
    gakuenKakumeidenMitsurugiNakayoshi: "Gakuen Kakumeiden Mitsurugi Nakayoshi",
    gekkouNoCarnevale: "Gekkou no Carnevale",
    gintama: "Gintama",
    granblueFantasy: "Granblue Fantasy",
    grisaiaNoKajitsu: "Grisaia no Kajitsu",
    guiltyCrown: "Guilty Crown",
    guiltyCrownLostChristmas: "Guilty Crown: Lost Christmas",
    gundamSeedDestiny: "Gundam Seed Destiny",
    heavyObject: "Heavy Object",
    hyperdimensionNeptunia: "Hyperdimension Neptunia",
    hyakko: "Hyakko",
    ikkitousen: "Ikkitousen",
    inuXBokuSs: "Inu x Boku SS",
    kakuSanSeiMillionArthur: "Kaku-San-Sei Million Arthur",
    kamigamiNoAsobi: "Kamigami no Asobi",
    kanon: "Kanon",
    karasuTenguUjuNagoMix: "Karasu Tengu Uju Nago Mix",
    karneval: "Karneval",
    katahaneShirohane: "Katahane Shirohane",
    kerli: "Kerli",
    kinoNoTabi: "Kino no Tabi",
    kyoukaiNoShirayuki: "Kyoukai no Shirayuki",
    ladyGaga: "Lady Gaga",
    lineageIi: "Lineage II",
    leagueOfAngels: "League of Angels",
    leagueOfLegends: "League of Legends",
    legendOfTheCryptids: "Legend of the Cryptids",
    loveless: "Loveless",
    mabinogi: "Mabinogi",
    magnaCarta: "Magna Carta",
    meriChri: "Meri Chri",
    moeMoeNijiTaisen: "Moe Moe Niji Taisen",
    mondaijiTachi: "Mondaiji-tachi ga Isekai kara Kuru Sou desu yo?",
    nagiNoAsukara: "Nagi no Asukara",
    nier: "Nier",
    noGameNoLife: "No Game No Life",
    noMoreHeroes: "No More Heroes",
    noragami: "Noragami",
    notLives: "Not Lives",
    okaneGaNai: "Okane ga Nai",
    osananajimiWaDaitouryou: "Osananajimi wa Daitouryou",
    overwatch: "Overwatch",
    pandorasTower: "Pandora's Tower",
    paradiseKiss: "Paradise Kiss",
    paraSol: "Para-sol",
    pause: "+pause+",
    persona4DancingAllNight: "Persona 4: Dancing All Night",
    persona5: "Persona 5",
    personaQShadowOfTheLabyrinth: "Persona Q: Shadow of Labyrinth",
    personaQ2NewCinemaLabyrinth: "Persona Q2: New Cinema Labyrinth",
    phantomBreaker: "Phantom Breaker",
    phantomOfInferno: "Phantom of Inferno",
    pokemon: "Pokemon",
    primaryMagicalTroubleScramble: "Primary Magical Trouble Scramble",
    qqFantasyWorld: "QQ Fantasy World",
    qqFengShenJi: "QQ Feng Shen Ji",
    qqXianXiaZhuan: "QQ Xian Xia Zhuan",
    queensBlade: "Queen's Blade",
    rageOfBahamut: "Rage of Bahamut",
    ragnaBreak: "Ragna Break",
    rayGigant: "Ray Gigant",
    rozenMaiden: "Rozen Maiden",
    sailorMoon: "Sailor Moon",
    sakuraHime: "Sakura Hime",
    samuraiJupiter: "Samurai Jupiter",
    shakuganNoShana: "Shakugan no Shana",
    shangriLa: "Shangri La",
    shinMegamiTenseiPersona3: "Shin Megami Persona 3",
    shinMegamiTenseiPersona4: "Shin Megami Persona 4",
    shinigamiNoTestament: "Shinigami no Testament",
    shiningForceExa: "Shining Force EXA",
    shiningResonance: "Shining Resonance",
    simoun: "Simoun",
    sisterPrincess: "Sister Princess",
    soniComi: "SoniComi",
    soraKakeGirl: "Sora Kake Girl",
    spiceWolf: "Spice & Wolf",
    steinsgate: "Steins;Gate",
    swordArtOnline: "Sword Art Online",
    swordGirls: "Sword Girls",
    tenjhoTenge: "Tenjho Tenge",
    tekken: "Tekken",
    tengenToppaGurrenLagann: "Tengen Toppa Gurren Lagann",
    terraBattle: "Terra Battle",
    thDragon2020: "7th Dragon 2020",
    theTaleOfAncientSwords: "The Legend of the Ancient Sword Online",
    theWitchAndTheHundredKnight: "The Witch and the Hundred Knight",
    timeAndEternity: "Time and Eternity",
    tokyoGhoul: "Tokyo Ghoul",
    tokyoMewMew: "Tokyo Mew Mew",
    touhou: "Touhou",
    trigun: "Trigun",
    trillionGodOfDestruction: "Trillion: God of Destruction",
    trinityBlood: "Trinity Blood",
    trinitySeven: "Trinity Seven",
    tsubasaReservoirChronicle: "Tsubasa Reservoir Chronicle",
    vampireKnight: "VampireKnight",
    vTR: "V.T.R",
    vocaloid: "Vocaloid",
    warOfGenesisIii: "War of Genesis III",
    winterTheme: "Winter theme",
    worldOfWarcraft: "World of Warcraft",
    x: 'X',
    xenosaga: "Xenosaga",
    xxxHoLiC: "xxxHOLiC",
    yamiToBoushiToHonNoTabibito: "Yami to Bōshi to Hon no Tabibito",
    yourName: "Your Name",
    yuruCamp: "Yuru Camp",
    zettaiNaruIsolator: "Zettai Naru Isolator"
};